### ISSUE TITLE
[BUG] error: the argument '--wordlist <FILE>' cannot be used multiple times

### ISSUE THREAD

**Issue by therohitdas** [epi052/feroxbuster#1046]
I am unable to use this tool as it is not loading the wordlist properly on MacOS.

I downloaded using the `brew install feroxbuter` command on MacOS 14.2.1.
I downloaded the wordlist and stored it in this directory:
`/Users/therohitdas/.local/wordlists`

I tried using two methods to tell feroxbuster about my wordlist:
1. By using the config file located I created it at `/Users/therohitdas/Library/Application Support/feroxbuster` as per the doc.
```toml
# wordlist = "/Users/therohitdas/.local/wordlists/combined_words.txt"
wordlist = "/Users/therohitdas/.local/wordlists/combined_directories.txt"


# extract_links = true # to find all visible and invisible links
random_agent = true
time-limit = "10m"
auto-tune = true
```
I get this error:
```bash
Could not open /Users/therohitdas/.local/wordlists/seclists/Discovery/
```
2. By using the command line argument after commenting out the wordlist var in the config: 
```bash
feroxbuster -u "https://localhost/" -w "/Users/therohitdas/.local/wordlists/combined_directories.txt"
```
I get this error:
```bash
error: the argument '--wordlist <FILE>' cannot be used multiple times

Usage: feroxbuster [OPTIONS]

For more information, try '--help'.
```

**Environment (please complete the following information):**
 - feroxbuster version: 2.10.1
 - OS: macOS 14.2.1
 - CPU: (8) arm64 Apple M1 Pro
 - Memory: 83.61 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
